export const FETCH_ITEMS_REQUEST = "FETCH_ITEMS_REQUEST";
export const FETCH_ITEMS_SUCCESS = "FETCH_ITEMS_SUCCESS";
export const FETCH_ITEMS_FAILURE = "FETCH_ITEMS_FAILURE";
export const FETCH_ITEMS_BY_FILTER_REQUEST = "FETCH_ITEMS_BY_FILTER_REQUEST";