export const FETCH_ITEM_TYPES_REQUEST = "FETCH_ITEM_TYPES_REQUEST";
export const FETCH_ITEM_TYPES_SUCCESS = "FETCH_ITEM_TYPES_SUCCESS";
export const FETCH_ITEM_TYPES_FAILURE = "FETCH_ITEM_TYPES_FAILURE";